### ISSUE TITLE
How active is this repo

### ISSUE THREAD

**Issue by karneaud** [jtpio/twin-fusion#6]
Hello,

I was lokkig for a game server engine with this sort of game principles in mind. Is this repo still maintained?

**Comment by jtpio** [comment]
This game was created during a game jam and occasionally updated afterwards.
But as many other game jams projects it kind of lost traction...

**Comment by karneaud** [comment]
@jtpio thanks for the response. I think I was interested more in the server side of things.... just to note maybe you should look at a port to http://www.airconsole.com

**Comment by jtpio** [comment]
There are definitely new solutions and alternatives for this kind of use case that popped up in the meantime (like the one you mentioned).
Another one would be [Jackbox](https://jackboxgames.com/how-to-play/), not sure how open their platform is though.
